source("tools/00-funs.R", echo = TRUE)

gert::git_pull(
  repo = ".sync/dplyr-main"
)

copy_dplyr_test <- function(test_name) {
  source <- fs::path(
    ".sync/dplyr-main/tests/testthat",
    test_name
  )
  target <- fs::path(
    "tests/testthat",
    gsub(
      "^(test|helper)-",
      "\\1-dplyr-",
      test_name
    )
  )

  rx <- paste0(
    "((?<![a-z_])(?:",
    paste(
      df_methods$name[
        !df_methods$skip_impl
      ],
      collapse = "|"
    ),
    ")[(])"
  )

  text <- brio::read_lines(source)
  text <- gsub(
    rx,
    "duckplyr_\\1",
    text,
    perl = TRUE
  )
  text <- text[grep(
    'skip_if(Sys.getenv("DUCKPLYR_FORCE") == "TRUE")',
    text,
    invert = TRUE,
    fixed = TRUE
  )]
  text <- text[grep(
    'skip("TODO duckdb")',
    text,
    invert = TRUE,
    fixed = TRUE
  )]

  skip_todo <- duckplyr_tests[[
    test_name
  ]]
  if (!is.null(skip_todo)) {
    skip_todo <- gsub(
      rx,
      "duckplyr_\\1",
      skip_todo,
      perl = TRUE
    )
    skip_todo_lines <- unique(unlist(map(
      paste0('"', skip_todo, '"'),
      grep,
      text,
      fixed = TRUE
    )))
    text[skip_todo_lines] <- paste0(
      text[skip_todo_lines],
      '\n  skip("TODO duckdb")'
    )
  }

  skip_force <- non_force_only_tests[[
    test_name
  ]]
  if (!is.null(skip_force)) {
    skip_force <- gsub(
      rx,
      "duckplyr_\\1",
      skip_force,
      perl = TRUE
    )
    skip_force_lines <- unique(unlist(map(
      paste0('"', skip_force, '"'),
      grep,
      text,
      fixed = TRUE
    )))
    text[skip_force_lines] <- paste0(
      text[skip_force_lines],
      '\n  skip_if(Sys.getenv("DUCKPLYR_FORCE") == "TRUE")'
    )
  }

  text <- c(
    "# Gezznezzrated by 04-dplyr-tests.R, do not edit by hand",
    "",
    if (grepl("^test-", test_name)) {
      c(
        "# Workaround for lazytest",
        'test_that("Dummy", { expect_true(TRUE) })',
        "",
        'skip_if(Sys.getenv("DUCKPLYR_SKIP_DPLYR_TESTS") == "TRUE")',
        ""
      )
    },
    text
  )

  brio::write_lines(text, target)

  target
}

targets <- map_chr(
  names(duckplyr_tests),
  copy_dplyr_test
)

system2("air", c("format", targets))

lock_dplyr_test <- function(path) {
  text <- brio::read_lines(path)
  text[[1]] <- "# Generated by 04-dplyr-tests.R, do not edit by hand"

  brio::write_lines(text, path)
}

walk(targets, lock_dplyr_test)

# Patch files -------------------------------------------------------------------------

# Apply manual tweaks (e.g. snapshot scrubbers) on top of the generated test
# files, mirroring the patch workflow in 02-duckplyr_df-methods.R.
patches <- fs::dir_ls("patch-tests")

walk(
  patches,
  ~ system(paste0("patch -p1 < ", .x))
)

# Stop here to overwrite files if the test generation is updated

# Collect new patches -----------------------------------------------------------------

test_status <- gert::git_status(
  pathspec = "tests/testthat/test-dplyr-*.R"
)$file

# Use this to refresh all patches
# test_status <- fs::dir_ls("tests/testthat", glob = "test-dplyr-*.R")

walk(test_status, function(file) {
  patch_path <- gsub(
    "tests/testthat/(.*)[.]R",
    "patch-tests/\\1.patch",
    file
  )
  if (fs::file_exists(patch_path)) {
    system(paste0(
      "patch -p1 -R < ",
      patch_path
    ))
  }
  system(paste0(
    "git diff -R -- ",
    file,
    " | grep -v '^index' > ",
    patch_path
  ))
  system(paste0(
    "git checkout -- ",
    file
  ))
})
